version: "3"

services:
  app:
    build: "."
    volumes:
      - ".:/app"
    ports:
      - "8080:8080"
    depends_on:
        - mariadb
    environment:
      - "WEB_DOCUMENT_ROOT=/app/public"
  mariadb:
    image: 'mariadb:latest'
    expose:
        - 3306
